import About from '@/components/About'
import Contact from '@/components/Contact'
import Features from '@/components/Features'
import Hero from '@/components/Hero'
import FloatingImage from '@/components/Story'
import Universe from '@/components/Universe'
import WhoAreWe from '@/components/WhoAreWe'
import Glance from '@/components/Glance'
import Labels from '@/components/Labels'
import Updates from '@/components/Updates'
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

function App() {
  return (
          <>
            <Hero />
            <About />
            <Features />
            <FloatingImage />
            <Universe />
            <WhoAreWe />
            <Glance />
            <Labels />
            <Updates />
            <Contact />
          </>

  )
}

export default App;